# Kong Gateway Configuration for ERPX AI
# =======================================

_format_version: "3.0"
_transform: true

services:
  # API Service
  - name: erpx-api
    url: http://api:8000
    routes:
      - name: api-route
        paths:
          - /api
        strip_path: true
        
      - name: health-route
        paths:
          - /health
        methods:
          - GET
        strip_path: false
          
      - name: upload-route
        paths:
          - /v1/upload
        methods:
          - POST
        strip_path: false
          
      - name: jobs-route
        paths:
          - /v1/jobs
        strip_path: false
          
      - name: approve-route
        paths:
          - /v1/approve
        methods:
          - POST
        strip_path: false

      # Testbench routes
      - name: testbench-tools-route
        paths:
          - /v1/testbench/tools
        methods:
          - GET
        strip_path: false
          
      - name: testbench-run-route
        paths:
          - /v1/testbench/run
        methods:
          - POST
        strip_path: false

      # Approvals routes
      - name: approvals-pending-route
        paths:
          - /v1/approvals/pending
        methods:
          - GET
        strip_path: false

      - name: approvals-action-route
        paths:
          - /v1/approvals
        strip_path: false

      # Evidence route
      - name: evidence-route
        paths:
          - /v1/evidence
        methods:
          - GET
        strip_path: false

      # Journal Proposals route (unauthenticated for UI)
      - name: journal-proposals-route
        paths:
          - /v1/journal-proposals
        methods:
          - GET
        strip_path: false

      # Journal Proposals route via /api prefix
      - name: journal-proposals-api-route
        paths:
          - /api/v1/journal-proposals
        methods:
          - GET
        strip_path: true

plugins:
  # JWT Authentication - Keycloak OIDC
  # Applied to ALL routes except health check and testbench
  - name: jwt
    route: api-route
    config:
      key_claim_name: iss
      claims_to_verify:
        - exp
      run_on_preflight: false
      
  - name: jwt
    route: upload-route
    config:
      key_claim_name: iss
      claims_to_verify:
        - exp
      run_on_preflight: false
      
  - name: jwt
    route: jobs-route
    config:
      key_claim_name: iss
      claims_to_verify:
        - exp
      run_on_preflight: false
      
  - name: jwt
    route: approve-route
    config:
      key_claim_name: iss
      claims_to_verify:
        - exp
      run_on_preflight: false
  
  # Rate limiting
  - name: rate-limiting
    config:
      minute: 100
      policy: local
      
  # CORS
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - X-Tenant-Id
        - X-Trace-Id
      exposed_headers:
        - X-Request-Id
      credentials: true
      max_age: 3600
      
  # Request logging
  - name: file-log
    config:
      path: /dev/stdout
      reopen: true
      
  # Request ID
  - name: correlation-id
    config:
      header_name: X-Request-Id
      generator: uuid
      echo_downstream: true


# Consumer for API access with Keycloak JWT
consumers:
  - username: keycloak-users
    custom_id: keycloak-erpx
    jwt_secrets:
      # Production HTTPS issuer (current)
      - key: https://auth.welliam.codes/realms/erpx
        algorithm: RS256
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8dOhgLYwfmpARYeW4440
          wbwIEBxyeF4+0Of/EcEnwQBMr0TrImuxLHKW/rIO5nPR+50RROL+F8v7fPEHifBc
          xnWUg4AhHqC6YfmuR5N+b4dywObd3qdljc1WhgSzJXrqUw5b51HIlOeQYIkrBoVT
          k5LuOUXG1uDdLBI4wZCW4Hwy4pLfMXtvNw7UCNh59RoTfiWbdX7KidTJNA1pImXO
          S7wKN+z169ozgy8dFe25572qNKtCjABo1LnvkoMDzwjkEYzLf8lbHAqdBgtFNIwX
          nTV9U5ZzUNVA+qNse4LmDE62+w9EtavoiJ85hyYtgy9eEYuJC3TWjsIzBeP1uIra
          QQIDAQAB
          -----END PUBLIC KEY-----
      # Legacy HTTP issuer (backward compatibility)
      - key: http://auth.welliam.codes/realms/erpx
        algorithm: RS256
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8dOhgLYwfmpARYeW4440
          wbwIEBxyeF4+0Of/EcEnwQBMr0TrImuxLHKW/rIO5nPR+50RROL+F8v7fPEHifBc
          xnWUg4AhHqC6YfmuR5N+b4dywObd3qdljc1WhgSzJXrqUw5b51HIlOeQYIkrBoVT
          k5LuOUXG1uDdLBI4wZCW4Hwy4pLfMXtvNw7UCNh59RoTfiWbdX7KidTJNA1pImXO
          S7wKN+z169ozgy8dFe25572qNKtCjABo1LnvkoMDzwjkEYzLf8lbHAqdBgtFNIwX
          nTV9U5ZzUNVA+qNse4LmDE62+w9EtavoiJ85hyYtgy9eEYuJC3TWjsIzBeP1uIra
          QQIDAQAB
          -----END PUBLIC KEY-----
      # Local development issuer
      - key: http://localhost:8180/realms/erpx
        algorithm: RS256
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8dOhgLYwfmpARYeW4440
          wbwIEBxyeF4+0Of/EcEnwQBMr0TrImuxLHKW/rIO5nPR+50RROL+F8v7fPEHifBc
          xnWUg4AhHqC6YfmuR5N+b4dywObd3qdljc1WhgSzJXrqUw5b51HIlOeQYIkrBoVT
          k5LuOUXG1uDdLBI4wZCW4Hwy4pLfMXtvNw7UCNh59RoTfiWbdX7KidTJNA1pImXO
          S7wKN+z169ozgy8dFe25572qNKtCjABo1LnvkoMDzwjkEYzLf8lbHAqdBgtFNIwX
          nTV9U5ZzUNVA+qNse4LmDE62+w9EtavoiJ85hyYtgy9eEYuJC3TWjsIzBeP1uIra
          QQIDAQAB
          -----END PUBLIC KEY-----
